server:
  port: 8080
---  

jwt:
  secret: secret123
  token:
    validity: 6000000
  refreshToken:
    validity: 9000000
---
#spring:
#  datasource:
#    url: jdbc:mysql://localhost/sansys_login_db?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#    username: root
#    password: root
#---

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:sansys_login_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin
    
---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
